vich_uploader:
    db_driver: orm

    mappings:
        post_featured_image:
            uri_prefix: /images/posts/featured
            upload_destination: '%kernel.project_dir%/public/images/posts/featured'

        tag_image:
            uri_prefix: /images/tags
            upload_destination: '%kernel.project_dir%/public/images/tags'
